### PR TITLE
Fix build error on Fedora 28 and add RPM packaging

### PR DESCRIPTION
**Pull request by jar1karp**
Hi,

I was getting linker errors when building the latest master from Github due to missing AlignedAllocate/AlignedDeallocate. It seems that this happens because CRYPTOPP_DISABLE_ASM is erroneusly defined by a typo in version check for GNU assembler.

This PR includes a commit to fix that typo, and in addition the version of cryptopp (minor thing probably as it's linked statically).

Finally, I added initial support for building an RPM package.

### CODE REVIEW

**Comment by netheril96** [comment]
I like what you are doing, but 

* It builds only a RPM package, but that is not reflected in the updated readme.
* The `Crypto++` cmake file is adapted from https://github.com/noloader/cryptopp-cmake/blob/master/CMakeLists.txt. I didn't bother to update it because it built without errors on my machine. I intend to override your changes by adapting from the newest version from that repo, since it may contain many other build fixes.

**Comment by jar1karp** [comment]
Ok, I'll update the readme. Probably .deb (and binary .tgz) packaging could be added also, I just need to setup a vm to test it properly. Seems that the bug that breaks as version detection is also in the cmake file in noloader repo as well. Weird that it hasn't been caught by anyone else.

**Comment by netheril96** [comment]
Maybe you could also submit a PR to noloader's repo? It would save me some manual fix if I copy from his/her repo again in the future.

**Comment by netheril96** [comment]
I manually updated the `CMakeLists.txt` from upstream in commit bb3cc575ca0c752f480d796b3faa2da5550bc890. If you wish to add the packaging functionality to `securefs`, please submit a separate PR.

**Pull request closed without merging**
